### ISSUE TITLE
original dataset

### ISSUE THREAD

**Issue by SISTMrL** [RomeroBarata/human_object_interaction#12]
hello, i saw the cad120 and bimanual datasets have been preprocessed, could you please provide the original datasets through goolge drive? the original datasets' link seems to be down, thus i can't download them from internet, looking forward to your reply, thanks!

**Comment by RomeroBarata** [comment]
Hi SISTMrL,

I should be able to upload parts of the CAD-120 dataset, but due to lack of space in my Google Drive we will have to coordinate it (I upload, you download, I delete, I upload more, etc.). Can you contact me at romero.morais@deakin.edu.au so that we can organise it? Thanks.

The original Bimanual dataset is quite big so I think it's best to contact the original authors (check why it is not online anymore). Can you email them and check if they can put it back online? When I had questions about the data the main author was very helpful. This is the reference paper for it: `Dreher, C. R., Wächter, M., & Asfour, T. (2020). Learning Object-Action Relations from Bimanual Human Demonstration Using Graph Networks. IEEE Robotics and Automation Letters, 5(1), 187–194.`.

Finally, I haven't forgot about the other issues you opened, I just haven't had enough time to look through them. As soon as I have some spare time I'll check them. Thanks.

Kind regards,
Romero

**Comment by SISTMrL** [comment]
Hello, RomeroBarata
I have sent the email to you, email: liuzhch1123@gmail.com
thanks very much!!!!
