### ISSUE TITLE
ground_truth_json file

### ISSUE THREAD

**Issue by tanqiu98** [RomeroBarata/human_object_interaction#2]
Hi Romero,

Could you provide the _ground_truth_json_ file of the CAD-120 dataset? It will be convenient for us to extract GT.

Many thanks,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

I don't remember having a ground-truth json file for the CAD-120 dataset. If I remember correctly I would just extract the ground-truth from the provided files in the CAD-120 dataset.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Could you point out which file in the CAD-120 dataset provides the ground-truth of sub-activity and affordance labels that match the video id?

Many thanks,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

You should be able to find the ground-truth for sub-activity and affordance labels, extracted by me, in the CAD-120/features/preprocessed/cad120data.pickle file. Otherwise, you will need to crawl through the original files provided by the CAD-120 authors to grab them; the function I used for that is `parse_cad120_information` in the `vhoi/cad120.py` file.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

I got the ground-truth for sub-activity and affordance labels extracted from you. Highly appreciate for your explanation.

Kind regards,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

No worries, I'm glad it helped.

Kind regards,
Romero
